services:
  arangodb:
    image: arangodb:3.12
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=greenapple71  # user root
      - ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES=2
      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=2G
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
    networks:
      - arango_net

  python_app:
    build: .
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    ports:
      - "7860:7860"
    depends_on:
      - arangodb
    networks:
      - arango_net

volumes:
  arangodb_data:

networks:
  arango_net:
    driver: bridge
